"""Generate the structural variants of the paper-faithful `wats_sewer_khalil`
network. Mirrors the extension chain applied to the extended model, but on the
faithful base. Run from this directory:

    python _make_khalil_variants.py

Produces wats_sewer_khalil_{halforder,directsulfate,srbsubstrate,combined}.yaml.
"""
from __future__ import annotations

import copy
import os

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.join(HERE, "wats_sewer_khalil.yaml")

# AD-safe half-order (sqrt) terms: x * (x + eps)^(-1/2) ~= sqrt(x), finite at 0.
# eps=1e-2 (rather than 1e-3) softens the steep slope at low concentration so the
# stiff-solver Jacobian / adjoint stays well-conditioned during gradient-based fits.
HALFORDER_EXPR = {
    "ho_sumS_half": "[sumS] * ([sumS] + 1.0e-2) ** (0.0 - 0.5)",
    "ho_XS0_half":  "[X_S0] * ([X_S0] + 1.0e-2) ** (0.0 - 0.5)",
    "ho_SNO_half":  "[S_NO] * ([S_NO] + 1.0e-2) ** (0.0 - 0.5)",
}


def rxn(net, name):
    for r in net["reactions"]:
        if r["name"] == name:
            return r
    raise KeyError(name)


def apply_halforder(net):
    net["expressions"].update(HALFORDER_EXPR)
    rxn(net, "sulfide_oxidation_anoxic_biofilm")["rate"] = \
        "k_sII_anox_f * ho_sumS_half * ho_SNO_half * {A_V}"
    rxn(net, "elemental_S_oxidation_anoxic_biofilm")["rate"] = \
        "k_s0_anox_f * ho_XS0_half * ho_SNO_half * {A_V}"


def apply_directsulfate(net):
    # Sulfide is oxidized straight to sulfate in one step (same total nitrate,
    # -0.225 - 0.525 = -0.75), bypassing the elemental-sulfur intermediate.
    rxn(net, "sulfide_oxidation_anoxic_biofilm")["stoichiometry"] = \
        {"sumS": -1, "S_SO4": 1, "S_NO": -0.75}


def apply_srbsubstrate(net):
    # Sulfate / elemental-S reduction consume readily-biodegradable substrate
    # (S_B) rather than VFA, so VFA accumulates as a fermentation product.
    net["reactions"] = [r for r in net["reactions"]
                        if r["name"] not in ("sulfate_reduction_VFA_biofilm",
                                             "elemental_S_reduction_VFA_biofilm")]
    net["reactions"] += [
        {"name": "sulfate_reduction_SB_biofilm",
         "description": "S_B-driven sulfate reduction to sulfide, biofilm.",
         "rate": "k_h2s_acid * monod([S_B], k_srb) * monod([S_SO4], k_so4) * no_gate * {A_V}",
         "stoichiometry": {"S_B": -2, "sumS": 1, "S_SO4": -1}},
        {"name": "elemental_S_reduction_SB_biofilm",
         "description": "S_B-driven reduction of elemental sulfur to sulfide, biofilm.",
         "rate": "k_s0_acid * monod([S_B], k_srb) * monod([X_S0], K_S0) * no_gate * {A_V}",
         "stoichiometry": {"S_B": -0.75, "sumS": 1, "X_S0": -1}},
    ]


VARIANTS = {
    "halforder": ("Half-order (square-root) kinetics for the nitrate-driven biofilm "
                  "sulfur-oxidation reactions, in place of the Monod terms.",
                  [apply_halforder]),
    "directsulfate": ("Nitrate-driven sulfide oxidation proceeds directly to sulfate "
                      "in one step, bypassing the elemental-sulfur intermediate.",
                      [apply_directsulfate]),
    "srbsubstrate": ("Sulfate and elemental-sulfur reduction consume readily-"
                     "biodegradable substrate (S_B) rather than VFA.",
                     [apply_srbsubstrate]),
    "combined": ("All three structural changes applied together.",
                 [apply_halforder, apply_directsulfate, apply_srbsubstrate]),
}


def main():
    base = yaml.safe_load(open(BASE))
    for key, (desc, fns) in VARIANTS.items():
        net = copy.deepcopy(base)
        net["network"]["name"] = f"wats_sewer_khalil_{key}"
        net["network"]["description"] = (
            f"Structural variant of wats_sewer_khalil. {desc} "
            f"All other reactions, parameters, species and conditions are "
            f"identical to the faithful base model. Auto-generated by "
            f"_make_khalil_variants.py.")
        for fn in fns:
            fn(net)
        out = os.path.join(HERE, f"wats_sewer_khalil_{key}.yaml")
        with open(out, "w") as f:
            f.write("# Auto-generated from wats_sewer_khalil.yaml by "
                    "_make_khalil_variants.py -- do not edit by hand.\n")
            yaml.safe_dump(net, f, sort_keys=False, default_flow_style=False, width=100)
        print(f"wrote {os.path.basename(out)}  ({len(net['reactions'])} reactions)")


if __name__ == "__main__":
    main()
