"""Generate wats_sewer_khalil_paper_balanced.yaml: the mass- and electron-balanced
"improved" counterpart of the faithful wats_sewer_khalil_paper model.

It is the faithful paper model (same kinetics, same electron-balanced sulfur
stoichiometry) plus two physically-motivated extensions that the published model
omits but the data and conservation laws require:

  1. FeS precipitation -- ferrous iron precipitates dissolved sulfide as solid
     FeS (Nielsen et al. 2005; SeweX/SUMO chemistry). The published model's iron
     chemistry is commented out, leaving a sulfur imbalance (the measured
     effluent sulfide is below the reduced-sulfate level); this closes it.
  2. Full nitrogen tracking -- the faithful paper model omits ammonia uptake on
     growth, ammonia release on hydrolysis, and ammonification on biomass decay,
     so it does not conserve nitrogen. The WATS N-content terms (i_n_bio, i_p_bio
     on biomass, i_n_xb on particulate substrate) are restored so the model
     conserves N and P.

The two models are intended to be run side by side to quantify what these
corrections buy. Run from this directory:  python _make_khalil_balanced.py
"""

from __future__ import annotations

import os

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.join(HERE, "wats_sewer_khalil_paper.yaml")
OUT = os.path.join(HERE, "wats_sewer_khalil_paper_balanced.yaml")

# Nitrogen / phosphorus content parameters (WATS/ASM stoichiometric coefficients).
N_PARAMS = {
    "i_n_bio": (0.07, "gN/gCOD", "N content of biomass"),
    "i_p_bio": (0.02, "gP/gCOD", "P content of biomass"),
    "i_n_xb": (0.07, "gN/gCOD", "N content of particulate substrate"),
}
FES_PARAM = ("k_fes_p", 1.0, "m3/g/d", "FeS precipitation rate (iron-limited 2nd-order)")

# composition: the conserved-quantity content (check_conservation table). Fe(II)
# carries 0.143 gCOD/gFe; solid FeS its mass fractions (Fe 56/88, S 32/88) with
# the residual COD, so the FeS-precipitation reaction closes COD / S / Fe.
FES_SPECIES = [
    {
        "name": "S_Fe2",
        "description": "Dissolved ferrous iron Fe(II)",
        "units": "gFe/m3",
        "default_concentration": 0.0,
        "composition": {"COD": 0.143, "Fe": 1.0},
    },
    {
        "name": "X_FeS",
        "description": "Precipitated iron sulfide FeS (solid)",
        "units": "gFeS/m3",
        "default_concentration": 0.0,
        "composition": {"COD": 0.818, "S": 32.0 / 88.0, "Fe": 56.0 / 88.0},
    },
]
FES_REACTION = {
    "name": "FeS_precipitation",
    "description": "Precipitation of dissolved sulfide with ferrous iron to solid "
    "FeS (Nielsen et al. 2005). Iron-limited second-order rate; "
    "mass fractions per g FeS: Fe 56/88, S 32/88.",
    "rate": "k_fes_p * [S_Fe2] * [sumS]",
    "stoichiometry": {"S_Fe2": -0.6364, "sumS": -0.3636, "X_FeS": 1},
}


def _num(v):
    return v if isinstance(v, (int, float)) else None


def main():
    net = yaml.safe_load(open(BASE))
    net["network"]["name"] = "wats_sewer_khalil_paper_balanced"
    net["network"]["description"] = (
        "Mass- and electron-balanced 'improved' counterpart of "
        "wats_sewer_khalil_paper: the faithful published Khalil (2025) model plus "
        "two conservation-restoring extensions it omits -- (1) FeS precipitation "
        "(ferrous iron precipitates sulfide as solid FeS, closing the sulfur "
        "balance against the measured effluent), and (2) full nitrogen/phosphorus "
        "tracking (ammonia uptake on growth, release on hydrolysis, and "
        "ammonification on biomass decay), so the model conserves N and P. "
        "Generated by _make_khalil_balanced.py for side-by-side comparison with "
        "the faithful model."
    )

    # (1) Restore N/P composition parameters.
    for name, (val, units, comment) in N_PARAMS.items():
        net["parameters"][name] = {"value": val, "units": units}
    fp_name, fp_val, fp_units, _ = FES_PARAM
    net["parameters"][fp_name] = {"value": fp_val, "units": fp_units}

    # (2) Restore the WATS nitrogen/phosphorus terms on the carbon reactions.
    #     Growth assimilates ammonia/phosphate into biomass; hydrolysis releases
    #     the particulate organic N as ammonia; biomass decay ammonifies.
    for rx in net["reactions"]:
        st = rx["stoichiometry"]
        xbh = _num(st.get("X_BH"))
        if xbh is not None and xbh > 0:  # growth: assimilation
            st.setdefault("S_NH", "0.0 - i_n_bio")
            st.setdefault("S_PO4", "0.0 - i_p_bio")
        elif xbh is not None and xbh < 0:  # biomass decay: ammonification
            st.setdefault("S_NH", "i_n_bio")
            st.setdefault("S_PO4", "i_p_bio")
        elif (_num(st.get("X_S1")) or 0) < 0 or (_num(st.get("X_S2")) or 0) < 0:
            st.setdefault("S_NH", "i_n_xb")  # hydrolysis: ammonia release

    # (3) Peer-review structural corrections (Reviewer 1 / Batstone, Khalil 2025):
    #   (a) Sulfide formers consume FERMENTABLE substrate S_B, not VFA -- so VFA
    #       (acetate) accumulates as a byproduct, as observed. Khalil's published
    #       model used VFA-only, which the reviewers called "simply wrong".
    #   (b) Revert Khalil's undocumented anoxic-VFA-uptake throttle (0.01/Y, found
    #       only in his code) to the standard 1/Y yield. The balanced model
    #       conserves COD and does not rely on that non-conservative hack.
    for rx in net["reactions"]:
        nm = rx["name"]
        if nm in ("sulfate_reduction_VFA_biofilm", "elemental_S_reduction_VFA_biofilm"):
            rx["name"] = nm.replace("_VFA_", "_SB_")
            rx["rate"] = rx["rate"].replace("[S_VFA]", "[S_B]")
            st = rx["stoichiometry"]
            st["S_B"] = st.pop("S_VFA")
            rx["description"] = (
                "Sulfide formation on fermentable substrate S_B "
                "(VFA accumulates as byproduct; peer review)."
            )
        if nm.startswith("anox_growth_VFA"):
            st = rx["stoichiometry"]
            if isinstance(st.get("S_VFA"), str) and "0.01" in st["S_VFA"]:
                st["S_VFA"] = "0.0 - 1.0 / y_h"

    # (4) Add FeS precipitation (species + reaction).
    net["species"].extend(FES_SPECIES)
    net["reactions"].append(FES_REACTION)

    with open(OUT, "w") as f:
        f.write(
            "# Auto-generated from wats_sewer_khalil_paper.yaml by "
            "_make_khalil_balanced.py -- do not edit by hand.\n"
        )
        yaml.safe_dump(net, f, sort_keys=False, default_flow_style=False, width=100)
    print(
        f"wrote {os.path.basename(OUT)} "
        f"({len(net['reactions'])} reactions, {len(net['species'])} species)"
    )


if __name__ == "__main__":
    main()
