"""Generate wats_sewer_khalil_paper_balanced_biofilm.yaml: the layered-biofilm
variant of the balanced model, for use with aquakin.BiofilmReactor.

The lumped balanced model applies the biofilm chemistry to a single well-mixed
bulk concentration scaled by an area-to-volume factor {A_V}. That cannot
represent processes controlled by how far a solute penetrates the biofilm --- in
particular, nitrate consumed in the outer layers never reaches the deep
methanogens, whose acetate uptake is then diffusion-limited, while deep
fermentation sustains the VFA pool (Sun et al. 2014; Jiang et al. 2009). A
depth-resolved reactor is required to capture this.

The chemistry is *unchanged* --- the only network surgery is to make the
bulk/biofilm phase of every reaction explicit so the reactor can run bulk
reactions in the well-mixed bulk and biofilm reactions in the layers:

  - 10 bulk-suspended reactions carry the suspended biomass [X_BH];
  - 12 biofilm reactions carry the area factor {A_V} (areal rate constants);
  - 3 chemical/abiotic reactions are bulk-phase;
  - 3 reactions (hydrolysis_fast, hydrolysis_slow, fermentation) act in BOTH
    phases via the composite biomass term bio_hf = [X_BH] + eps*{X_BF}*{A_V}.

This generator splits those 3 composite reactions into a `_bulk` half (biomass
[X_BH]) and a `_biofilm` half (biomass eps*{X_BF}*{A_V}); summed they reproduce
the lumped rate exactly, so the lumped model is the well-mixed limit of the
layered one. No rate constants change.

To use the variant: the biofilm reactions are those whose rate references {A_V}
(the 12 originals + the 3 new `_biofilm` halves). Pass their names as
``biofilm_reactions`` to BiofilmReactor, and set the per-layer area factor
``A_V = 1 / thickness`` (the areal rate constants are per m^2 of biofilm; with a
biofilm of thickness L_f resolved into layers this recovers the lumped A_V flux
to the bulk in the well-mixed limit, conserving mass).

Run from this directory:  python _make_khalil_balanced_biofilm.py
"""
from __future__ import annotations

import os

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.join(HERE, "wats_sewer_khalil_paper_balanced.yaml")
OUT = os.path.join(HERE, "wats_sewer_khalil_paper_balanced_biofilm.yaml")

# The composite "both-phase" reactions and the two halves of bio_hf.
SPLIT = ("hydrolysis_fast", "hydrolysis_slow", "fermentation")
BULK_BIOMASS = "[X_BH]"
FILM_BIOMASS = "(eps * {X_BF} * {A_V})"


def main():
    net = yaml.safe_load(open(BASE))
    net["network"]["name"] = "wats_sewer_khalil_paper_balanced_biofilm"
    net["network"]["description"] = (
        "Layered-biofilm variant of wats_sewer_khalil_paper_balanced for use "
        "with aquakin.BiofilmReactor. Identical chemistry, but the three "
        "composite bulk+biofilm reactions (hydrolysis_fast/slow, fermentation) "
        "are split into explicit _bulk ([X_BH]) and _biofilm (eps*{X_BF}*{A_V}) "
        "halves so the reactor can run bulk-suspended reactions in the well-mixed "
        "bulk and biofilm reactions ({A_V}) in the depth-resolved layers. The "
        "lumped balanced model is the well-mixed limit of this network. "
        "Generated by _make_khalil_balanced_biofilm.py.")

    out_reactions = []
    n_split = 0
    for rx in net["reactions"]:
        if rx["name"] in SPLIT and "bio_hf" in rx["rate"]:
            n_split += 1
            for suffix, biomass in (("_bulk", BULK_BIOMASS), ("_biofilm", FILM_BIOMASS)):
                half = {
                    "name": rx["name"] + suffix,
                    "description": rx.get("description", "").rstrip(".")
                    + f" ({suffix[1:]} phase).",
                    "rate": rx["rate"].replace("bio_hf", biomass),
                    "stoichiometry": dict(rx["stoichiometry"]),
                }
                # carry any reaction-local parameters/reference unchanged
                for k, v in rx.items():
                    if k not in half:
                        half[k] = v
                out_reactions.append(half)
        else:
            out_reactions.append(rx)
    net["reactions"] = out_reactions

    # bio_hf is now unused (every reference was split away); drop it.
    if "expressions" in net and "bio_hf" in net["expressions"]:
        del net["expressions"]["bio_hf"]

    with open(OUT, "w") as f:
        f.write("# Auto-generated from wats_sewer_khalil_paper_balanced.yaml by "
                "_make_khalil_balanced_biofilm.py -- do not edit by hand.\n")
        yaml.safe_dump(net, f, sort_keys=False, default_flow_style=False, width=100)

    biofilm_rxns = [r["name"] for r in net["reactions"] if "{A_V}" in r["rate"]]
    print(f"wrote {os.path.basename(OUT)} "
          f"({len(net['reactions'])} reactions, {len(net['species'])} species; "
          f"split {n_split} composite reactions)")
    print(f"  biofilm reactions ({len(biofilm_rxns)}): {biofilm_rxns}")


if __name__ == "__main__":
    main()
