"""One-shot generator for BSM1 influent CSV fixtures.

Produces ``aquakin/plant/bsm/data/BSM1_{dry,rain,storm}.csv`` using the
BSM1 average composition documented in Copp 2002 Table 5.1, plus a
diurnal pattern of the right magnitude. Note: these files are
**synthesised** — they match the BSM1 *statistical* profile but are NOT
the canonical CSVs distributed by the IWA Task Group. For published
comparisons (EQI / OCI matching Alex 2008 to ~1%), users should replace
these with the official files.

Run once at repo setup; the resulting CSVs are committed as package data.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np


# BSM1 average dry-weather influent (Copp 2002 Table 5.1).
# Concentrations in g/m³; alkalinity in mol HCO3⁻/m³; Q in m³/d.
_BSM1_DRY_AVG = {
    "SI":   30.0,
    "SS":   69.5,
    "XI":   51.2,
    "XS":  202.32,
    "XB_H": 28.17,
    "XB_A":  0.0,
    "XP":    0.0,
    "SO":    0.0,
    "SNO":   0.0,
    "SNH":  31.56,
    "SND":   6.95,
    "XND":  10.59,
    "SALK":  7.0,
}
_BSM1_Q_AVG = 18446.0  # m³/d

_COLUMN_ORDER = [
    "t", "SI", "SS", "XI", "XS", "XB_H", "XB_A", "XP",
    "SO", "SNO", "SNH", "SND", "XND", "SALK", "Q",
]

# Per Alex et al. 2008: dry weather has a 14-day record with a 24-hour
# diurnal period and ±30% amplitude variation on flow and major species.
# Rain and storm are dry with overlaid increased flow events.

_OUTPUT_DIR = Path(__file__).resolve().parents[1] / "aquakin" / "plant" / "bsm" / "data"


def _diurnal_pattern(t_days: np.ndarray, amp: float = 0.3) -> np.ndarray:
    """A simple smooth diurnal pattern with the morning/evening peaks
    characteristic of municipal sewage. Mean is 1.0, amplitude controlled
    by ``amp``."""
    omega = 2.0 * np.pi  # 1/day
    return 1.0 + amp * (
        0.6 * np.sin(omega * t_days - 0.3)
        + 0.4 * np.sin(2 * omega * t_days + 0.7)
    )


def _generate_dry(n_days: int = 14, dt_min: int = 15) -> np.ndarray:
    """14 days of dry-weather influent at 15-minute resolution."""
    n_per_day = (24 * 60) // dt_min
    n_t = n_days * n_per_day + 1
    t = np.linspace(0.0, n_days, n_t)
    pattern = _diurnal_pattern(t)
    rng = np.random.default_rng(0)
    noise = 1.0 + 0.05 * rng.standard_normal(n_t)
    rows = []
    for ti, p, n in zip(t, pattern, noise):
        row = [ti]
        for sp in _COLUMN_ORDER[1:-1]:
            mean = _BSM1_DRY_AVG[sp]
            # Particulates and SS swing with pattern (settling load
            # tracks flow); inerts stay constant; oxygen/nitrate stay 0.
            if mean == 0.0:
                val = 0.0
            elif sp in ("SI", "XI"):
                val = mean * n  # near-constant
            else:
                val = mean * p * n
            row.append(val)
        row.append(_BSM1_Q_AVG * p * n)
        rows.append(row)
    return np.asarray(rows)


def _generate_rain(n_days: int = 14, dt_min: int = 15) -> np.ndarray:
    """Dry-weather + a 24-hour rain event starting at day 9."""
    arr = _generate_dry(n_days, dt_min)
    n_per_day = (24 * 60) // dt_min
    start = 9 * n_per_day
    end = start + n_per_day
    # Rain event: flow doubles, soluble concentrations halve (dilution),
    # particulates roughly maintain due to wash-off.
    for i in range(start, end):
        frac = (i - start) / n_per_day
        intensity = 4.0 * frac * (1.0 - frac)  # parabolic; peak ≈ 1.0
        arr[i, _COLUMN_ORDER.index("Q")] *= (1.0 + intensity)
        for sp in ("SS", "SNH", "SND"):
            arr[i, _COLUMN_ORDER.index(sp)] *= (1.0 - 0.4 * intensity)
    return arr


def _generate_storm(n_days: int = 14, dt_min: int = 15) -> np.ndarray:
    """Dry-weather + two short, intense storm events."""
    arr = _generate_dry(n_days, dt_min)
    n_per_day = (24 * 60) // dt_min
    # Two 6-hour storms.
    storm_duration = n_per_day // 4
    for storm_start_day in (8, 11):
        start = storm_start_day * n_per_day + n_per_day // 2
        end = start + storm_duration
        for i in range(start, end):
            frac = (i - start) / storm_duration
            intensity = 4.0 * frac * (1.0 - frac)
            arr[i, _COLUMN_ORDER.index("Q")] *= (1.0 + 2.5 * intensity)
            for sp in ("SS", "SNH"):
                arr[i, _COLUMN_ORDER.index(sp)] *= (1.0 - 0.6 * intensity)
    return arr


_HEADER = (
    "# BSM1-style influent (synthesised, not the canonical IWA file).\n"
    "# Generated by scripts/generate_bsm1_influent.py at repo setup.\n"
    "# Profile follows Copp 2002 Table 5.1 average composition plus a\n"
    "# diurnal flow / load pattern. Replace with the official BSM1 file\n"
    "# for published-EQI comparisons.\n"
    "# Columns: " + ",".join(_COLUMN_ORDER) + "\n"
)


def _write_csv(data: np.ndarray, path: Path) -> None:
    with path.open("w") as f:
        f.write(_HEADER)
        f.write(",".join(_COLUMN_ORDER) + "\n")
        for row in data:
            f.write(",".join(f"{v:.6g}" for v in row) + "\n")
    print(f"Wrote {path} ({data.shape[0]} rows)")


def main() -> None:
    _OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    _write_csv(_generate_dry(), _OUTPUT_DIR / "BSM1_dry.csv")
    _write_csv(_generate_rain(), _OUTPUT_DIR / "BSM1_rain.csv")
    _write_csv(_generate_storm(), _OUTPUT_DIR / "BSM1_storm.csv")


if __name__ == "__main__":
    main()
