"""One-shot generator for BSM2 influent CSV fixtures.

Produces ``aquakin/plant/bsm/data/BSM2_{dry,rain,storm}.csv`` using the BSM2
constant-influent composition (the published open-loop operating point) plus a
diurnal pattern and wet-weather events of the right magnitude. Note: these files
are **synthesised** -- they match the BSM2 *statistical* profile but are NOT the
canonical 609-day series distributed by the IWA Task Group. For published
comparisons, users should replace them with the official BSM2 influent file.

The columns mirror the BSM1 fixtures (``t``, the 13 ASM1 species, ``Q``); the
BSM2 reference file also carries TSS and a time-varying temperature, but
aquakin's ASM1 has no temperature dependence and the digester runs at a fixed
35 degC, so those are omitted (they would not change the simulation).

Run once at repo setup; the resulting CSVs are committed as package data.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np


# BSM2 constant-influent composition (the published open-loop operating point).
# Concentrations in g/m3; alkalinity in mol HCO3-/m3; Q in m3/d.
_BSM2_AVG = {
    "SI": 27.2262, "SS": 58.1762, "XI": 92.499, "XS": 363.9435, "XB_H": 50.6833,
    "XB_A": 0.0, "XP": 0.0, "SO": 0.0, "SNO": 0.0, "SNH": 23.8595, "SND": 5.6516,
    "XND": 16.1298, "SALK": 7.0,
}
_BSM2_Q_AVG = 20648.0  # m3/d

_COLUMN_ORDER = [
    "t", "SI", "SS", "XI", "XS", "XB_H", "XB_A", "XP",
    "SO", "SNO", "SNH", "SND", "XND", "SALK", "Q",
]

_OUTPUT_DIR = Path(__file__).resolve().parents[1] / "aquakin" / "plant" / "bsm" / "data"


def _diurnal_pattern(t_days: np.ndarray, amp: float = 0.3) -> np.ndarray:
    """A smooth diurnal pattern with morning/evening peaks; mean 1.0."""
    omega = 2.0 * np.pi  # 1/day
    return 1.0 + amp * (
        0.6 * np.sin(omega * t_days - 0.3)
        + 0.4 * np.sin(2 * omega * t_days + 0.7)
    )


def _generate_dry(n_days: int = 14, dt_min: int = 15) -> np.ndarray:
    """``n_days`` of dry-weather influent at ``dt_min``-minute resolution."""
    n_per_day = (24 * 60) // dt_min
    n_t = n_days * n_per_day + 1
    t = np.linspace(0.0, n_days, n_t)
    pattern = _diurnal_pattern(t)
    rng = np.random.default_rng(2)
    noise = 1.0 + 0.05 * rng.standard_normal(n_t)
    rows = []
    for ti, p, n in zip(t, pattern, noise):
        row = [ti]
        for sp in _COLUMN_ORDER[1:-1]:
            mean = _BSM2_AVG[sp]
            # Particulates / SS / N swing with the load pattern; inerts are
            # near-constant; oxygen / nitrate stay zero.
            if mean == 0.0:
                val = 0.0
            elif sp in ("SI", "XI"):
                val = mean * n
            else:
                val = mean * p * n
            row.append(val)
        row.append(_BSM2_Q_AVG * p * n)
        rows.append(row)
    return np.asarray(rows)


def _generate_rain(n_days: int = 14, dt_min: int = 15) -> np.ndarray:
    """Dry-weather + a 24-hour rain event starting at day 9."""
    arr = _generate_dry(n_days, dt_min)
    n_per_day = (24 * 60) // dt_min
    start = 9 * n_per_day
    end = start + n_per_day
    for i in range(start, end):
        frac = (i - start) / n_per_day
        intensity = 4.0 * frac * (1.0 - frac)  # parabolic; peak ~ 1.0
        arr[i, _COLUMN_ORDER.index("Q")] *= (1.0 + intensity)
        for sp in ("SS", "SNH", "SND"):
            arr[i, _COLUMN_ORDER.index(sp)] *= (1.0 - 0.4 * intensity)
    return arr


def _generate_storm(n_days: int = 14, dt_min: int = 15) -> np.ndarray:
    """Dry-weather + two short, intense storm events."""
    arr = _generate_dry(n_days, dt_min)
    n_per_day = (24 * 60) // dt_min
    storm_duration = n_per_day // 4
    for storm_start_day in (8, 11):
        start = storm_start_day * n_per_day + n_per_day // 2
        end = start + storm_duration
        for i in range(start, end):
            frac = (i - start) / storm_duration
            intensity = 4.0 * frac * (1.0 - frac)
            arr[i, _COLUMN_ORDER.index("Q")] *= (1.0 + 2.5 * intensity)
            for sp in ("SS", "SNH"):
                arr[i, _COLUMN_ORDER.index(sp)] *= (1.0 - 0.6 * intensity)
    return arr


_HEADER = (
    "# BSM2-style influent (synthesised, not the canonical IWA 609-day file).\n"
    "# Generated by scripts/generate_bsm2_influent.py at repo setup.\n"
    "# Profile follows the BSM2 constant-influent composition plus a diurnal\n"
    "# flow / load pattern. Replace with the official BSM2 file for published\n"
    "# comparisons. TSS and influent temperature are omitted (aquakin's ASM1 is\n"
    "# temperature-independent; the digester runs at a fixed 35 degC).\n"
    "# Columns: " + ",".join(_COLUMN_ORDER) + "\n"
)


def _write_csv(data: np.ndarray, path: Path) -> None:
    with path.open("w") as f:
        f.write(_HEADER)
        f.write(",".join(_COLUMN_ORDER) + "\n")
        for row in data:
            f.write(",".join(f"{v:.6g}" for v in row) + "\n")


def main() -> None:
    _OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    _write_csv(_generate_dry(), _OUTPUT_DIR / "BSM2_dry.csv")
    _write_csv(_generate_rain(), _OUTPUT_DIR / "BSM2_rain.csv")
    _write_csv(_generate_storm(), _OUTPUT_DIR / "BSM2_storm.csv")
    print(f"Wrote BSM2_{{dry,rain,storm}}.csv to {_OUTPUT_DIR}")


if __name__ == "__main__":
    main()
