"""Plant flowsheet assembly and monolithic Diffrax integration.

A :class:`Plant` owns a set of :class:`Unit`-Protocol-conforming components,
the directed connections between them, and time-varying influent sources.
Calling :meth:`Plant.solve` builds one flat state vector by concatenating
each unit's internal state, integrates the whole thing under Diffrax, and
returns a :class:`PlantSolution`.

The RHS uses a two-pass design per evaluation:

1. **Stream pass** — walk units in evaluation order, computing each unit's
   output streams from its current internal state and its input streams.
   Internal recycles work naturally because output streams are functions
   of *current* state, not future state.
2. **Derivative pass** — compute each unit's ``dstate`` from its current
   state and input streams (now all known from pass 1). Concatenate.

The evaluation order is the user-supplied unit ordering. Cycles in the
connection graph are allowed (recycles); the user marks edges that close
cycles by ordering downstream units before upstream consumers — see
:meth:`Plant.connect` documentation.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Optional, Union

import diffrax
import jax
import jax.numpy as jnp

from aquakin.core.network import CompiledNetwork
from aquakin.integrate._common import _coerce_atol, _run_diffeqsolve
from aquakin.plant.influent import InfluentSeries
from aquakin.plant.streams import Stream, StreamSeries
from aquakin.plant.translators import IdentityTranslator, StateTranslator
from aquakin.plant.units import Unit


@dataclass(frozen=True)
class Connection:
    """A directed stream connection between two units (or from an influent
    source). ``from_unit=None`` indicates the source is an external
    influent named by ``from_port``; otherwise ``from_port`` is one of
    ``from_unit.output_ports``."""

    from_unit: Optional[str]
    from_port: str
    to_unit: str
    to_port: str
    translator: StateTranslator
    initial_value: Optional[Stream] = None  # used to seed recycle edges on the first pass


@dataclass
class ParameterLayout:
    """Maps named slices of the flat plant parameter vector to network /
    plant-level concerns.

    For BSM1 every CSTR uses the same ASM1 network so we have *one*
    kinetic-parameter block.

    The layout is generated by :meth:`Plant._build_parameter_layout` from
    the network references on each unit. Users typically don't construct
    it directly.
    """

    network_param_blocks: dict[str, tuple[int, int]] = field(default_factory=dict)
    # (start_index, length) per kinetic network, keyed by network.name.
    # All units sharing a network see the same block.
    total_size: int = 0


@dataclass
class PlantSolution:
    """Result of :meth:`Plant.solve`.

    Attributes
    ----------
    t : jnp.ndarray
        Save times, shape ``(n_t,)``.
    state : jnp.ndarray
        Full plant state, shape ``(n_t, total_state_size)``.
    plant : Plant
        The plant that produced this solution; retained for accessor
        methods.
    """

    t: jnp.ndarray
    state: jnp.ndarray
    plant: "Plant"

    def unit_state(self, unit_name: str) -> jnp.ndarray:
        """Return the trajectory of one unit's state, shape
        ``(n_t, unit.state_size)``."""
        start, size = self.plant._state_layout[unit_name]
        return self.state[:, start : start + size]

    def C_named(self, unit_name: str, species: str) -> jnp.ndarray:
        """Return a single species' trajectory in a single unit.

        Only valid for units whose state is a concentration vector in
        the unit's network (CSTRs and other kinetic units).
        """
        unit = self.plant.units[unit_name]
        if not hasattr(unit, "network"):
            raise KeyError(
                f"Unit '{unit_name}' has no 'network' attribute; cannot "
                f"index by species name."
            )
        idx = unit.network.species_index[species]
        return self.unit_state(unit_name)[:, idx]


class Plant:
    """A plant flowsheet of :class:`Unit` components.

    Build a plant by:

    1. Constructing each unit (CSTRUnit, MixerUnit, etc.).
    2. Adding them via :meth:`add_unit` in the order you want their
       RHS evaluated (downstream-first if there's a recycle).
    3. Adding influent sources via :meth:`add_influent`.
    4. Connecting units via :meth:`connect`.
    5. Calling :meth:`solve`.

    Parameters
    ----------
    name : str
    recycle_passes : int, optional
        Number of Gauss-Seidel passes used per RHS evaluation to propagate
        concentrations around recycle loops (default 3). The recycle *flows*
        are resolved exactly (:meth:`_resolve_flows`); this only bounds the
        concentration sweep. It is a *fixed* count (not iterate-to-tolerance)
        because the RHS is jitted and differentiated, so a data-dependent loop
        is not permitted. For BSM-family topologies the streams reach a fixed
        point in 2 passes (verified to machine precision), so the default of 3
        is a safe margin; raise it only for unusual topologies with a long
        chain of concentration-transforming units (mixers/splitters/clarifiers)
        inside a recycle loop.
    """

    def __init__(self, name: str, *, recycle_passes: int = 3) -> None:
        self.name = name
        if recycle_passes < 1:
            raise ValueError(f"recycle_passes must be >= 1; got {recycle_passes}")
        self.recycle_passes = int(recycle_passes)
        self.units: dict[str, Unit] = {}
        self._unit_order: list[str] = []
        self.connections: list[Connection] = []
        self.influents: dict[str, InfluentSeries] = {}
        # Filled in at solve() time:
        self._state_layout: dict[str, tuple[int, int]] = {}
        self._total_state_size: int = 0
        self._parameter_layout: ParameterLayout = ParameterLayout()
        self._network_param_index: dict[str, int] = {}
        # Static connection adjacency, rebuilt by _build_state_layout():
        self._inputs_by_unit: dict[str, list[Connection]] = {}
        self._recycle_keys: list[tuple[Optional[str], str]] = []

    # ----- assembly --------------------------------------------------------

    def add_unit(self, unit: Unit) -> None:
        """Register a unit. Order of addition is the evaluation order."""
        if unit.name in self.units:
            raise ValueError(f"Unit '{unit.name}' already added")
        self.units[unit.name] = unit
        self._unit_order.append(unit.name)

    def add_influent(
        self,
        name: str,
        series: InfluentSeries,
        to: Optional[str] = None,
        *,
        translator: Optional[StateTranslator] = None,
    ) -> None:
        """Register an external time-varying influent stream, optionally wiring it.

        Parameters
        ----------
        name : str
            Identifier for this influent (used in stream keys and error
            messages).
        series : InfluentSeries
            The time-varying influent data.
        to : str, optional
            Destination endpoint to feed this influent into, as ``"unit.port"``
            (or bare ``"unit"`` to use the unit's sole input port). When given,
            the connection is made here, so no separate :meth:`connect` call is
            needed. The destination unit must already be added. When omitted the
            influent is registered but inert -- influents are not valid
            :meth:`connect` sources, so wiring happens here.
        translator : StateTranslator, optional
            Translator for the influent -> unit connection. Defaults to identity
            when the influent and destination share a network.
        """
        if name in self.influents:
            raise ValueError(f"Influent '{name}' already added")
        self.influents[name] = series
        if to is not None:
            to_unit, to_port = self._parse_endpoint(to, role="destination")
            translator = self._default_translator(
                series.network, to_unit, translator,
                f"influent '{name}'", f"{to_unit}.{to_port}",
            )
            self.connections.append(
                Connection(
                    from_unit=None, from_port=name,
                    to_unit=to_unit, to_port=to_port,
                    translator=translator, initial_value=None,
                )
            )

    def connect(
        self,
        source: str,
        dest: str,
        *,
        translator: Optional[StateTranslator] = None,
        initial_value: Optional[Stream] = None,
    ) -> None:
        """Wire a stream from one unit's output to another unit's input.

        Both endpoints are ``"unit.port"`` strings, read as ``source -> dest``.
        The port may be omitted (bare ``"unit"``) when the unit has exactly one
        port for that role -- a single output (source) or single input (dest) --
        so only multi-port units like mixers and splitters need an explicit
        port. To feed an external influent, use
        :meth:`add_influent` with ``to=...`` rather than :meth:`connect`.

        Parameters
        ----------
        source : str
            Source endpoint, ``"unit.port"`` or bare ``"unit"`` for the unit's
            sole output port.
        dest : str
            Destination endpoint, ``"unit.port"`` or bare ``"unit"`` for the
            unit's sole input port.
        translator : StateTranslator, optional
            State translator to apply as the stream crosses the connection.
            Defaults to :class:`IdentityTranslator` when source and destination
            share a network; required when they differ.
        initial_value : Stream, optional
            Seed for the stream's first RHS pass on a *recycle* edge (where the
            source unit is evaluated after the destination in
            :attr:`_unit_order`). Omit it and any recycle edge is auto-seeded
            with a zero-flow stream of the source network; pass it only to
            override that with a non-zero warm start. Ignored for feed-forward
            edges.

        Examples
        --------
        >>> plant.connect("tank1", "tank2")                 # sole ports inferred
        >>> plant.connect("tank5_split.to_clarifier", "clarifier")
        >>> plant.connect("split.recycle", "mix.recycle")   # recycle: auto-seeded
        """
        src_unit, src_port = self._parse_endpoint(source, role="source")
        dst_unit, dst_port = self._parse_endpoint(dest, role="destination")
        translator = self._default_translator(
            self._unit_network(src_unit), dst_unit, translator,
            f"{src_unit}.{src_port}", f"{dst_unit}.{dst_port}",
        )
        if initial_value is None and self._is_recycle(src_unit, dst_unit):
            net = self._unit_network(src_unit)
            initial_value = Stream(
                Q=jnp.asarray(0.0), C=net.default_concentrations(), network=net
            )
        self.connections.append(
            Connection(
                from_unit=src_unit, from_port=src_port,
                to_unit=dst_unit, to_port=dst_port,
                translator=translator, initial_value=initial_value,
            )
        )

    def _parse_endpoint(self, spec: str, *, role: str) -> tuple[str, str]:
        """Resolve a ``"unit.port"`` / ``"unit"`` endpoint string to ``(unit, port)``.

        ``role`` is ``"source"`` (resolves against the unit's output ports) or
        ``"destination"`` (input ports). A bare unit infers its sole port for
        that role; an unknown unit, an unknown port, or an ambiguous bare unit
        (more than one port for the role) raises a clear error.
        """
        unit_name, _, port = spec.partition(".")
        if unit_name not in self.units:
            if unit_name in self.influents:
                raise ValueError(
                    f"'{unit_name}' is an influent, not a unit; wire it with "
                    f"add_influent('{unit_name}', series, to=...), not connect()."
                )
            raise KeyError(f"Unknown unit '{unit_name}' in endpoint '{spec}'.")
        ports = (
            self.units[unit_name].output_ports if role == "source"
            else self.units[unit_name].input_ports
        )
        if port:
            if port not in ports:
                raise KeyError(
                    f"Unit '{unit_name}' has no {role} port '{port}'; "
                    f"available: {list(ports)}."
                )
            return unit_name, port
        if len(ports) != 1:
            raise ValueError(
                f"Endpoint '{spec}' omits the port, but unit '{unit_name}' has "
                f"{len(ports)} {role} ports {list(ports)}; name one explicitly "
                f"as '{unit_name}.<port>'."
            )
        return unit_name, ports[0]

    def _default_translator(
        self, source_network, dest_unit, translator, src_label, dst_label
    ) -> StateTranslator:
        """Return ``translator`` if given, else the default for the endpoints.

        The default is :class:`IdentityTranslator` when the source and
        destination share a network; a cross-network connection with no
        explicit translator is an error.
        """
        if translator is not None:
            return translator
        target_network = self._unit_network(dest_unit)
        if source_network is target_network:
            return IdentityTranslator(target_network)
        raise ValueError(
            f"Connection {src_label} -> {dst_label} crosses networks; "
            f"supply an explicit translator."
        )

    def _is_recycle(self, source_unit: str, dest_unit: str) -> bool:
        """True if ``source_unit`` is evaluated after ``dest_unit`` (a recycle)."""
        order = self._unit_order
        return order.index(source_unit) > order.index(dest_unit)

    def _unit_network(self, unit_name: str) -> CompiledNetwork:
        unit = self.units[unit_name]
        if not hasattr(unit, "network"):
            raise KeyError(
                f"Unit '{unit_name}' has no 'network' attribute; cannot "
                f"infer translator default."
            )
        return unit.network

    # ----- layout ----------------------------------------------------------

    def _build_state_layout(self) -> None:
        """Assign each unit a contiguous slice of the flat state vector.

        Also (re)builds the static connection-adjacency caches the RHS hot
        paths rely on (:meth:`_build_connection_index`). Both depend only on
        the wiring, which is fixed by the time the plant is solved, so they are
        computed together here -- the single topology-setup entry point that
        :meth:`solve` and every direct-RHS caller invoke first.
        """
        layout: dict[str, tuple[int, int]] = {}
        cursor = 0
        for name in self._unit_order:
            size = self.units[name].state_size
            layout[name] = (cursor, size)
            cursor += size
        self._state_layout = layout
        self._total_state_size = cursor
        self._build_connection_index()

    def _build_connection_index(self) -> None:
        """Precompute the static connection adjacency for the RHS hot paths.

        Two derived structures, both functions of the wiring only:

        - ``_inputs_by_unit`` groups connections by destination unit, so
          :meth:`_collect_inputs` and :meth:`_resolve_flows` look up a unit's
          incoming edges in O(in-degree) instead of re-scanning all
          connections (the scan ran ``recycle_passes x n_units`` times per
          stream sweep plus once per unit in the derivative pass).
        - ``_recycle_keys`` lists the recycle source ports (back-edges seeded
          with an ``initial_value``), so :meth:`_resolve_flows` does not
          re-derive them on every step.
        """
        inputs_by_unit: dict[str, list[Connection]] = {
            name: [] for name in self._unit_order
        }
        for conn in self.connections:
            inputs_by_unit.setdefault(conn.to_unit, []).append(conn)
        self._inputs_by_unit = inputs_by_unit
        self._recycle_keys = [
            (c.from_unit, c.from_port)
            for c in self.connections
            if c.from_unit is not None and c.initial_value is not None
        ]

    def _ordered_networks(self) -> list[CompiledNetwork]:
        """The distinct kinetic networks, in first-appearance order.

        Deduplicated by object **identity** (two units sharing the same
        compiled network see one block). Parameter blocks are keyed by
        ``network.name``, so two *distinct* networks sharing a name would
        collide; reject that here rather than silently mis-slice the
        parameter vector. This is the single source of truth for both
        :meth:`_build_parameter_layout` and :meth:`default_parameters`, so the
        layout and the default vector can never disagree.
        """
        seen: list[CompiledNetwork] = []
        for name in self._unit_order:
            net = getattr(self.units[name], "network", None)
            if net is None:
                continue
            if any(s is net for s in seen):
                continue
            if any(s.name == net.name for s in seen):
                raise ValueError(
                    f"Two distinct networks share the name '{net.name}'. "
                    f"Parameter blocks are keyed by network name, so names "
                    f"must be unique across the plant's networks."
                )
            seen.append(net)
        return seen

    def _build_parameter_layout(self) -> ParameterLayout:
        """Concatenate kinetic-parameter vectors for every distinct network.

        Each network contributes one block, in the order networks first
        appear via the unit-list iteration.
        """
        blocks: dict[str, tuple[int, int]] = {}
        cursor = 0
        net_index: dict[str, int] = {}
        for i, net in enumerate(self._ordered_networks()):
            blocks[net.name] = (cursor, net.n_params)
            net_index[net.name] = i
            cursor += net.n_params

        self._network_param_index = net_index
        self._parameter_layout = ParameterLayout(
            network_param_blocks=blocks,
            total_size=cursor,
        )
        return self._parameter_layout

    def default_parameters(self) -> jnp.ndarray:
        """Concatenated default parameters across all kinetic networks."""
        nets = self._ordered_networks()
        if not nets:
            return jnp.zeros((0,))
        return jnp.concatenate([net.default_parameters() for net in nets])

    def _params_for_unit(
        self, unit_name: str, params_full: jnp.ndarray
    ) -> jnp.ndarray:
        """Slice out the kinetic parameters for one unit's network."""
        unit = self.units[unit_name]
        net = getattr(unit, "network", None)
        if net is None:
            return jnp.zeros((0,))
        start, size = self._parameter_layout.network_param_blocks[net.name]
        return jax.lax.dynamic_slice(params_full, (start,), (size,))

    def initial_state(
        self, overrides: Optional[dict[str, jnp.ndarray]] = None
    ) -> jnp.ndarray:
        """Concatenated initial state from each unit's ``initial_state()``.

        Parameters
        ----------
        overrides : dict[str, array-like], optional
            Map of unit name to an initial-state vector that replaces that
            unit's own ``initial_state()``. Each vector must have length equal
            to the unit's ``state_size``. Use this to warm-start a plant --
            e.g. seed the activated-sludge reactors with a healthy biomass
            before settling a slow digester -- without reaching into the
            internal state layout::

                warm = asm1.concentrations(XB_H=2244.0, ...)   # (n_species,)
                y0 = plant.initial_state(overrides={t: warm for t in tanks})

        Returns
        -------
        jnp.ndarray
            The flat initial-state vector, shape ``(total_state_size,)``.

        Raises
        ------
        KeyError
            If an override names a unit not in the plant.
        ValueError
            If an override vector length does not match the unit's state size.
        """
        self._build_state_layout()
        if self._total_state_size == 0:
            return jnp.zeros((0,))
        overrides = overrides or {}
        unknown = set(overrides) - set(self.units)
        if unknown:
            raise KeyError(
                f"initial_state overrides name unknown units {sorted(unknown)}; "
                f"valid units are {sorted(self.units)}."
            )
        pieces: list[jnp.ndarray] = []
        for name in self._unit_order:
            if name in overrides:
                vec = jnp.asarray(overrides[name])
                expected = self.units[name].state_size
                if vec.shape != (expected,):
                    raise ValueError(
                        f"initial_state override for unit '{name}' has shape "
                        f"{vec.shape}, expected ({expected},)."
                    )
                pieces.append(vec)
            else:
                pieces.append(self.units[name].initial_state())
        return jnp.concatenate(pieces)

    # ----- RHS -------------------------------------------------------------

    def _split_state(
        self, state_full: jnp.ndarray
    ) -> dict[str, jnp.ndarray]:
        """Split the flat state vector into a per-unit ``{name: state}`` map."""
        states: dict[str, jnp.ndarray] = {}
        for name in self._unit_order:
            start, size = self._state_layout[name]
            states[name] = jax.lax.dynamic_slice(state_full, (start,), (size,))
        return states

    def _resolve_streams(
        self,
        t: jnp.ndarray,
        states: dict[str, jnp.ndarray],
        params_full: jnp.ndarray,
    ) -> tuple[
        dict[tuple[Optional[str], str], Stream],
        dict[tuple[str, str], Stream],
    ]:
        """Resolve every unit's output streams at one instant.

        Builds the influent + recycle-seed registry, resolves the (exact,
        concentration-decoupled) recycle flow network, and runs the fixed-pass
        Gauss-Seidel output sweep. Returns ``(all_outputs, influent_streams)``;
        the second is needed by :meth:`_collect_inputs`.
        """
        streams: dict[tuple[Optional[str], str], Stream] = {}
        for port_name, series in self.influents.items():
            streams[(None, port_name)] = series.at(t)
        resolved_flows = self._resolve_flows(t, params_full)
        seeded = self._seed_recycle_streams(resolved_flows)
        all_outputs = self._sweep_outputs(t, states, streams, seeded, params_full)
        return all_outputs, streams

    def outputs_at(
        self,
        t: jnp.ndarray,
        state_full: jnp.ndarray,
        params: Optional[jnp.ndarray] = None,
    ) -> dict[tuple[str, str], Stream]:
        """Reconstruct every unit's output streams at one ``(t, state)``.

        The plant integrates unit *states*, not the inter-unit streams, so a
        stream such as the clarifier effluent is recomputed from the state on
        demand. This resolves the full output sweep (including recycle edges)
        and returns the ``{(unit, port): Stream}`` map. See :meth:`stream` for
        a named-stream trajectory over a whole solution.

        Parameters
        ----------
        t : float
            Time (plant units), used to interpolate the influents.
        state_full : jnp.ndarray
            Flat plant state at ``t`` (e.g. one row of ``PlantSolution.state``).
        params : jnp.ndarray, optional
            Plant parameters (defaults to :meth:`default_parameters`).

        Returns
        -------
        dict
            ``{(unit_name, port_name): Stream}`` for every unit output.
        """
        self._build_state_layout()
        self._build_parameter_layout()
        params_full = (
            self.default_parameters() if params is None else jnp.asarray(params)
        )
        states = self._split_state(jnp.asarray(state_full))
        all_outputs, _ = self._resolve_streams(jnp.asarray(t), states, params_full)
        return all_outputs

    def stream(
        self,
        solution: "PlantSolution",
        endpoint: str,
        params: Optional[jnp.ndarray] = None,
    ) -> StreamSeries:
        """Reconstruct a named output stream's trajectory from a solution.

        Walks the solution's saved states and rebuilds one unit-output stream
        (flow + concentration over time) -- e.g. the secondary-clarifier
        effluent, which the plant does not store directly because it integrates
        unit states only.

        Parameters
        ----------
        solution : PlantSolution
            A solution returned by :meth:`solve` (carries ``t`` and ``state``).
        endpoint : str
            ``"unit.port"`` naming the output stream, e.g.
            ``"clarifier.overflow"``. The port may be omitted (bare ``"unit"``)
            for a single-output unit.
        params : jnp.ndarray, optional
            The plant parameters used for the run (defaults to
            :meth:`default_parameters`). Output reconstruction is
            parameter-independent for the shipped units, so the default is
            usually fine.

        Returns
        -------
        StreamSeries
            ``t``, ``Q``, ``C`` (shape ``(n_t, n_species)``) and ``network``,
            with a ``C_named(species)`` accessor.
        """
        unit, port = self._parse_endpoint(endpoint, role="source")
        params_full = (
            self.default_parameters() if params is None else jnp.asarray(params)
        )
        ts = solution.t
        Q_list, C_list = [], []
        for i in range(ts.shape[0]):
            outs = self.outputs_at(ts[i], solution.state[i], params_full)
            s = outs[(unit, port)]
            Q_list.append(s.Q)
            C_list.append(s.C)
        return StreamSeries(
            t=ts, Q=jnp.stack(Q_list), C=jnp.stack(C_list),
            network=self.units[unit].network,
        )

    def _rhs(
        self,
        t: jnp.ndarray,
        state_full: jnp.ndarray,
        params_full: jnp.ndarray,
    ) -> jnp.ndarray:
        # Step 1: split state by unit.
        states = self._split_state(state_full)

        # Steps 2-3: resolve influent + recycle streams and run the output sweep.
        all_outputs, streams = self._resolve_streams(t, states, params_full)

        # Step 3b: control signals (see :meth:`_compute_signals`).
        signals = self._compute_signals(t, states, all_outputs, streams,
                                        params_full)

        # Step 4: compute dstates from final input streams (and control signals).
        dstates: list[jnp.ndarray] = []
        for name in self._unit_order:
            unit = self.units[name]
            inputs = self._collect_inputs(name, all_outputs, streams)
            params_unit = self._params_for_unit(name, params_full)
            if getattr(unit, "consumes_signals", False):
                dstate = unit.rhs(t, states[name], inputs, params_unit, signals)
            else:
                dstate = unit.rhs(t, states[name], inputs, params_unit)
            dstates.append(dstate)
        return jnp.concatenate(dstates) if dstates else jnp.zeros((0,))

    def _compute_signals(
        self,
        t: jnp.ndarray,
        states: dict[str, jnp.ndarray],
        all_outputs: dict[tuple[str, str], Stream],
        streams: dict[tuple[Optional[str], str], Stream],
        params_full: jnp.ndarray,
    ) -> dict:
        """Gather the control-signal bus from every controller unit.

        Units exposing ``signal_outputs`` (e.g. PI controllers) read their
        sensed input streams and own state and write named scalar signals into a
        shared dict; units with ``consumes_signals`` (e.g. an aerated CSTR under
        DO control) read those signals in ``rhs``. The hooks are class-level, so
        the branch is static (jit-safe).
        """
        signals: dict = {}
        for name in self._unit_order:
            unit = self.units[name]
            if hasattr(unit, "signal_outputs"):
                inputs = self._collect_inputs(name, all_outputs, streams)
                signals.update(unit.signal_outputs(
                    t, states[name], inputs,
                    self._params_for_unit(name, params_full)))
        return signals

    def signals_at(
        self,
        t: jnp.ndarray,
        state_full: jnp.ndarray,
        params: Optional[jnp.ndarray] = None,
    ) -> dict:
        """Reconstruct the control-signal bus at one ``(t, state)``.

        The plant integrates unit states, not the control signals, so a signal
        such as a DO controller's manipulated ``kLa`` is recomputed from the
        state on demand -- the signal analogue of :meth:`outputs_at`. Returns
        ``{}`` for an open-loop plant (no controllers).

        Parameters
        ----------
        t : float
            Time (plant units), used to interpolate the influents.
        state_full : jnp.ndarray
            Flat plant state at ``t`` (e.g. one row of ``PlantSolution.state``).
        params : jnp.ndarray, optional
            Plant parameters (defaults to :meth:`default_parameters`).

        Returns
        -------
        dict
            ``{signal_name: scalar}`` for every published control signal.
        """
        self._build_state_layout()
        self._build_parameter_layout()
        params_full = (
            self.default_parameters() if params is None else jnp.asarray(params)
        )
        states = self._split_state(jnp.asarray(state_full))
        all_outputs, streams = self._resolve_streams(
            jnp.asarray(t), states, params_full)
        return self._compute_signals(
            jnp.asarray(t), states, all_outputs, streams, params_full)

    def _seed_recycle_streams(
        self,
        resolved_flows: dict[tuple[Optional[str], str], jnp.ndarray],
    ) -> dict[tuple[str, str], Stream]:
        """Pre-seed recycle back-edges with their resolved flow + initial conc.

        A recycle edge (downstream -> upstream) must be readable before its
        source unit has been visited in the sweep. We seed it with the
        exactly-resolved flow (from :meth:`_resolve_flows`) and the edge's
        declared ``initial_value`` concentration; the concentration is then
        corrected within a few sweep passes, as recycle concentrations are read
        directly from the source unit's state.
        """
        seeded: dict[tuple[str, str], Stream] = {}
        for conn in self.connections:
            if conn.from_unit is None or conn.initial_value is None:
                continue
            iv = conn.initial_value
            q = resolved_flows[(conn.from_unit, conn.from_port)]
            seeded[(conn.from_unit, conn.from_port)] = Stream(
                Q=q, C=iv.C, network=iv.network, T=iv.T
            )
        return seeded

    def _sweep_outputs(
        self,
        t: jnp.ndarray,
        states: dict[str, jnp.ndarray],
        streams: dict[tuple[Optional[str], str], Stream],
        seeded: dict[tuple[str, str], Stream],
        params_full: jnp.ndarray,
    ) -> dict[tuple[str, str], Stream]:
        """Resolve unit outputs with the fixed-pass Gauss-Seidel recycle sweep.

        Recycle edges (downstream -> upstream) create cyclic data dependencies.
        We resolve them with a fixed number of passes (``recycle_passes``,
        default 3) over the unit-output computations: each pass refines the
        stream estimates on recycle edges. The count is fixed, not
        iterate-to-tolerance, because this RHS is jitted and differentiated --
        a data-dependent loop is not allowed. Convergence is fast because most
        recycle-stream concentrations are a source unit's *state* (read
        directly, e.g. a CSTR's output is its own tank concentration), so the
        only iterated chain is the short mixer/splitter/clarifier path. For
        BSM-family topologies the streams reach a fixed point in 2 passes
        (verified to machine precision in tests/integration/test_bsm1.py), so
        the default 3 is a safe margin. ``streams`` is updated in place; the
        returned ``all_outputs`` includes the recycle seeds.
        """
        all_outputs: dict[tuple[str, str], Stream] = {}
        all_outputs.update(seeded)
        for _pass in range(self.recycle_passes):
            for name in self._unit_order:
                unit = self.units[name]
                inputs = self._collect_inputs(name, all_outputs, streams)
                params_unit = self._params_for_unit(name, params_full)
                outputs = unit.compute_outputs(t, states[name], inputs, params_unit)
                for port, stream in outputs.items():
                    all_outputs[(name, port)] = stream
                    streams[(name, port)] = stream
        return all_outputs

    def _resolve_flows(
        self, t: jnp.ndarray, params_full: jnp.ndarray
    ) -> dict[tuple[Optional[str], str], jnp.ndarray]:
        """Solve the recycle FLOW network exactly (decoupled from concentration).

        Every unit exposes a linear ``flow_outputs`` rule (output port flows from
        input port flows). One topological pass over those rules, with the
        recycle back-edges held at trial values, is an affine map
        ``x -> A x + b`` on the back-edge flows. We recover ``A`` and ``b`` by
        probing (one pass at zero, one per back-edge) and solve
        ``(I - A) x = b`` for the consistent recycle flows -- exact and
        gain-independent, in ``n_recycle + 1`` cheap scalar passes. Returns the
        resolved flow for every stream key.
        """
        base: dict[tuple[Optional[str], str], jnp.ndarray] = {}
        for port_name, series in self.influents.items():
            base[(None, port_name)] = series.at(t).Q
        recycle_keys = self._recycle_keys
        n = len(recycle_keys)

        def one_pass(recycle_Qs):
            flows = dict(base)
            for k, q in zip(recycle_keys, recycle_Qs):
                flows[k] = q
            for name in self._unit_order:
                in_flows: dict[str, jnp.ndarray] = {}
                for conn in self._inputs_by_unit.get(name, ()):
                    src = (None, conn.from_port) if conn.from_unit is None \
                        else (conn.from_unit, conn.from_port)
                    in_flows[conn.to_port] = flows[src]
                out = self.units[name].flow_outputs(
                    in_flows, self._params_for_unit(name, params_full)
                )
                for port, q in out.items():
                    flows[(name, port)] = q
            recycled = (
                jnp.stack([flows[k] for k in recycle_keys])
                if n else jnp.zeros((0,))
            )
            return recycled, flows

        if n == 0:
            return one_pass(jnp.zeros((0,)))[1]
        b, _ = one_pass(jnp.zeros((n,)))
        eye = jnp.eye(n)
        cols = [one_pass(eye[i])[0] - b for i in range(n)]
        A = jnp.stack(cols, axis=1)
        x = jnp.linalg.solve(eye - A, b)
        return one_pass(x)[1]

    def _collect_inputs(
        self,
        unit_name: str,
        all_outputs: dict[tuple[str, str], Stream],
        streams: dict[tuple[Optional[str], str], Stream],
    ) -> dict[str, Stream]:
        """Find the input stream for each port of ``unit_name``."""
        inputs: dict[str, Stream] = {}
        for conn in self._inputs_by_unit.get(unit_name, ()):
            if conn.from_unit is None:
                src = streams[(None, conn.from_port)]
            else:
                key = (conn.from_unit, conn.from_port)
                if key in all_outputs:
                    src = all_outputs[key]
                elif key in streams:
                    src = streams[key]
                else:
                    raise RuntimeError(
                        f"Stream {conn.from_unit}.{conn.from_port} not yet "
                        f"available for {conn.to_unit}.{conn.to_port}. "
                        f"Recycle edges must be seeded with initial_value."
                    )
            inputs[conn.to_port] = src.with_C(conn.translator.translate(src.C))
        return inputs

    # ----- solve -----------------------------------------------------------

    def solve(
        self,
        t_span: tuple[float, float],
        t_eval: Union[jnp.ndarray, None] = None,
        params: Optional[jnp.ndarray] = None,
        *,
        rtol: float = 1e-6,
        atol: Union[float, jnp.ndarray] = 1e-9,
        adjoint: Optional[diffrax.AbstractAdjoint] = None,
        dtmax: Optional[float] = None,
        max_steps: int = 100_000,
        y0: Optional[jnp.ndarray] = None,
    ) -> PlantSolution:
        """Integrate the plant over ``t_span``.

        Parameters
        ----------
        t_span : (float, float)
            ``(t_start, t_end)`` in plant time units (typically days for BSM-family).
        t_eval : jnp.ndarray, optional
            Save times. If ``None`` only the endpoint is saved.
        params : jnp.ndarray, optional
            Flat plant parameter vector. Defaults to :meth:`default_parameters`.
        rtol, atol : solver tolerances.
        adjoint : diffrax adjoint strategy.
        dtmax : float, optional
            Maximum integrator step (threaded into the PIDController). Default
            ``None`` (uncapped) is fastest for forward solves. Set it for a
            stiff plant when *differentiating* through the solve: the
            reverse-mode adjoint of stiff biofilm reactions returns non-finite
            values uncapped, and capping ``dtmax`` to a small multiple of the
            fastest reaction timescale restores finite gradients (same as the
            reactor ``dtmax``; see the stiff-network discussion in CLAUDE.md).
        max_steps : int, optional
            Maximum number of internal solver steps (default 100000). Increase
            it for stiff, long-horizon plants -- notably BSM1 with the Takács
            clarifier, whose 10-layer settling dynamics need a larger budget than
            the stateless ``IdealClarifier``.

        Returns
        -------
        PlantSolution
        """
        self._build_state_layout()
        layout = self._build_parameter_layout()
        if params is None:
            params = self.default_parameters()
        else:
            params = jnp.asarray(params)
            if params.shape != (layout.total_size,):
                raise ValueError(
                    f"params has shape {params.shape}, expected "
                    f"({layout.total_size},)"
                )
        atol_eff = _coerce_atol(atol, self._total_state_size)

        # Initial state: the per-unit defaults, or a caller-supplied warm start
        # (e.g. a previously-computed steady state -- the standard way to start a
        # dynamic-influent run, avoiding the stiff clean-start transient).
        if y0 is None:
            y0 = self.initial_state()
        else:
            y0 = jnp.asarray(y0)
            if y0.shape != (self._total_state_size,):
                raise ValueError(
                    f"y0 has shape {y0.shape}, expected ({self._total_state_size},)"
                )
        t0, t1 = float(t_span[0]), float(t_span[1])
        if not (t1 > t0):
            raise ValueError(f"t_span end must exceed start; got ({t0}, {t1}).")
        if t_eval is None:
            saveat = diffrax.SaveAt(t1=True)
        else:
            t_eval = jnp.asarray(t_eval)
            saveat = diffrax.SaveAt(ts=t_eval)

        # Closure-capture self and params; Diffrax sees a clean (t, y, args)
        # signature. We pass params via args so jax.grad through params
        # works.
        def rhs(t, y, args):
            return self._rhs(t, y, args)

        sol = _run_diffeqsolve(
            rhs,
            t0=t0,
            t1=t1,
            y0=y0,
            args=params,
            saveat=saveat,
            rtol=rtol,
            atol=atol_eff,
            adjoint=adjoint,
            dtmax=dtmax,
            max_steps=max_steps,
        )
        return PlantSolution(t=sol.ts, state=sol.ys, plant=self)
