"""Plant flowsheet assembly and monolithic Diffrax integration.

A :class:`Plant` owns a set of :class:`Unit`-Protocol-conforming components,
the directed connections between them, and time-varying influent sources.
Calling :meth:`Plant.solve` builds one flat state vector by concatenating
each unit's internal state, integrates the whole thing under Diffrax, and
returns a :class:`PlantSolution`.

The RHS uses a two-pass design per evaluation:

1. **Stream pass** — walk units in evaluation order, computing each unit's
   output streams from its current internal state and its input streams.
   Internal recycles work naturally because output streams are functions
   of *current* state, not future state.
2. **Derivative pass** — compute each unit's ``dstate`` from its current
   state and input streams (now all known from pass 1). Concatenate.

The evaluation order is the user-supplied unit ordering. Cycles in the
connection graph are allowed (recycles); the user marks edges that close
cycles by ordering downstream units before upstream consumers — see
:meth:`Plant.connect` documentation.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Optional, Union

import diffrax
import jax
import jax.numpy as jnp

from aquakin.core.network import CompiledNetwork
from aquakin.integrate._common import _coerce_atol, _run_diffeqsolve
from aquakin.plant.influent import InfluentSeries
from aquakin.plant.streams import Stream
from aquakin.plant.translators import IdentityTranslator, StateTranslator
from aquakin.plant.units import Unit


@dataclass(frozen=True)
class Connection:
    """A directed stream connection between two units (or from an influent
    source). ``from_unit=None`` indicates the source is an external
    influent named by ``from_port``; otherwise ``from_port`` is one of
    ``from_unit.output_ports``."""

    from_unit: Optional[str]
    from_port: str
    to_unit: str
    to_port: str
    translator: StateTranslator
    initial_value: Optional[Stream] = None  # used to seed recycle edges on the first pass


@dataclass
class ParameterLayout:
    """Maps named slices of the flat plant parameter vector to network /
    plant-level concerns.

    For BSM1 every CSTR uses the same ASM1 network so we have *one*
    kinetic-parameter block. Plant-level scalars (kLa, recycle ratios,
    DO setpoint) follow.

    The layout is generated by :meth:`Plant._build_parameter_layout` from
    the network references on each unit. Users typically don't construct
    it directly.
    """

    network_param_blocks: dict[str, tuple[int, int]] = field(default_factory=dict)
    # (start_index, length) per kinetic network, keyed by network.name.
    # All units sharing a network see the same block.
    plant_scalar_block: tuple[int, int] = (0, 0)
    # Reserved for future plant-level scalar parameters (kLa, recycle
    # ratios, etc.). Currently always empty — BSM1 hardcodes these in
    # unit constructors.
    total_size: int = 0


@dataclass
class PlantSolution:
    """Result of :meth:`Plant.solve`.

    Attributes
    ----------
    t : jnp.ndarray
        Save times, shape ``(n_t,)``.
    state : jnp.ndarray
        Full plant state, shape ``(n_t, total_state_size)``.
    plant : Plant
        The plant that produced this solution; retained for accessor
        methods.
    """

    t: jnp.ndarray
    state: jnp.ndarray
    plant: "Plant"

    def unit_state(self, unit_name: str) -> jnp.ndarray:
        """Return the trajectory of one unit's state, shape
        ``(n_t, unit.state_size)``."""
        start, size = self.plant._state_layout[unit_name]
        return self.state[:, start : start + size]

    def C_named(self, unit_name: str, species: str) -> jnp.ndarray:
        """Return a single species' trajectory in a single unit.

        Only valid for units whose state is a concentration vector in
        the unit's network (CSTRs and other kinetic units).
        """
        unit = self.plant.units[unit_name]
        if not hasattr(unit, "network"):
            raise KeyError(
                f"Unit '{unit_name}' has no 'network' attribute; cannot "
                f"index by species name."
            )
        idx = unit.network.species_index[species]
        return self.unit_state(unit_name)[:, idx]


class Plant:
    """A plant flowsheet of :class:`Unit` components.

    Build a plant by:

    1. Constructing each unit (CSTRUnit, MixerUnit, etc.).
    2. Adding them via :meth:`add_unit` in the order you want their
       RHS evaluated (downstream-first if there's a recycle).
    3. Adding influent sources via :meth:`add_influent`.
    4. Connecting units via :meth:`connect`.
    5. Calling :meth:`solve`.

    Parameters
    ----------
    name : str
    """

    def __init__(self, name: str) -> None:
        self.name = name
        self.units: dict[str, Unit] = {}
        self._unit_order: list[str] = []
        self.connections: list[Connection] = []
        self.influents: dict[str, InfluentSeries] = {}
        # Filled in at solve() time:
        self._state_layout: dict[str, tuple[int, int]] = {}
        self._total_state_size: int = 0
        self._parameter_layout: ParameterLayout = ParameterLayout()
        self._network_param_index: dict[str, int] = {}

    # ----- assembly --------------------------------------------------------

    def add_unit(self, unit: Unit) -> None:
        """Register a unit. Order of addition is the evaluation order."""
        if unit.name in self.units:
            raise ValueError(f"Unit '{unit.name}' already added")
        self.units[unit.name] = unit
        self._unit_order.append(unit.name)

    def add_influent(self, port_name: str, series: InfluentSeries) -> None:
        """Register an external time-varying influent stream.

        ``port_name`` is the symbolic name used as ``from_port`` in a
        connection (with ``from_unit=None``).
        """
        if port_name in self.influents:
            raise ValueError(f"Influent '{port_name}' already added")
        self.influents[port_name] = series

    def connect(
        self,
        from_unit: Optional[str],
        from_port: str,
        to_unit: str,
        to_port: str,
        translator: Optional[StateTranslator] = None,
        initial_value: Optional[Stream] = None,
    ) -> None:
        """Wire one stream from a source to a destination.

        Parameters
        ----------
        from_unit : str or None
            Source unit name, or ``None`` for an external influent.
        from_port : str
            Source port name. For an influent, this is the influent's
            registered name.
        to_unit : str
            Destination unit name.
        to_port : str
            Destination input port name on the destination unit.
        translator : StateTranslator, optional
            State translator to apply on the stream as it crosses the
            connection. Defaults to :class:`IdentityTranslator` when
            source and destination share a network. Required when they
            differ.
        initial_value : Stream, optional
            Seed value for the stream on the first RHS pass. Required for
            *recycle* edges (where the source unit is evaluated after the
            destination unit in :attr:`_unit_order`). Ignored for
            feed-forward edges.
        """
        if to_unit not in self.units:
            raise KeyError(f"Unknown destination unit '{to_unit}'")
        if from_unit is not None and from_unit not in self.units:
            raise KeyError(f"Unknown source unit '{from_unit}'")
        if from_unit is None and from_port not in self.influents:
            raise KeyError(f"Unknown influent '{from_port}'")
        if to_port not in self.units[to_unit].input_ports:
            raise KeyError(
                f"Unit '{to_unit}' has no input port '{to_port}'; available: "
                f"{self.units[to_unit].input_ports}"
            )
        # Resolve a default translator if both ends share a network.
        if translator is None:
            target_network = self._unit_network(to_unit)
            source_network = (
                self._unit_network(from_unit)
                if from_unit is not None
                else self.influents[from_port].network
            )
            if source_network is target_network:
                translator = IdentityTranslator(target_network)
            else:
                raise ValueError(
                    f"Connection {from_unit}.{from_port} -> {to_unit}.{to_port} "
                    f"crosses networks; supply an explicit translator."
                )
        self.connections.append(
            Connection(
                from_unit=from_unit,
                from_port=from_port,
                to_unit=to_unit,
                to_port=to_port,
                translator=translator,
                initial_value=initial_value,
            )
        )

    def _unit_network(self, unit_name: str) -> CompiledNetwork:
        unit = self.units[unit_name]
        if not hasattr(unit, "network"):
            raise KeyError(
                f"Unit '{unit_name}' has no 'network' attribute; cannot "
                f"infer translator default."
            )
        return unit.network

    # ----- layout ----------------------------------------------------------

    def _build_state_layout(self) -> None:
        """Assign each unit a contiguous slice of the flat state vector."""
        layout: dict[str, tuple[int, int]] = {}
        cursor = 0
        for name in self._unit_order:
            size = self.units[name].state_size
            layout[name] = (cursor, size)
            cursor += size
        self._state_layout = layout
        self._total_state_size = cursor

    def _build_parameter_layout(self) -> ParameterLayout:
        """Concatenate kinetic-parameter vectors for every distinct network.

        Each network contributes one block, in the order networks first
        appear via the unit-list iteration.
        """
        seen: list[CompiledNetwork] = []
        for name in self._unit_order:
            unit = self.units[name]
            net = getattr(unit, "network", None)
            if net is None:
                continue
            if not any(s is net for s in seen):
                seen.append(net)

        blocks: dict[str, tuple[int, int]] = {}
        cursor = 0
        net_index: dict[str, int] = {}
        for i, net in enumerate(seen):
            blocks[net.name] = (cursor, net.n_params)
            net_index[net.name] = i
            cursor += net.n_params

        self._network_param_index = net_index
        self._parameter_layout = ParameterLayout(
            network_param_blocks=blocks,
            plant_scalar_block=(cursor, 0),
            total_size=cursor,
        )
        return self._parameter_layout

    def default_parameters(self) -> jnp.ndarray:
        """Concatenated default parameters across all kinetic networks."""
        layout = self._build_parameter_layout()
        if layout.total_size == 0:
            return jnp.zeros((0,))
        pieces: list[jnp.ndarray] = []
        seen_names: set[str] = set()
        for name in self._unit_order:
            unit = self.units[name]
            net = getattr(unit, "network", None)
            if net is None or net.name in seen_names:
                continue
            seen_names.add(net.name)
            pieces.append(net.default_parameters())
        return jnp.concatenate(pieces)

    def _params_for_unit(
        self, unit_name: str, params_full: jnp.ndarray
    ) -> jnp.ndarray:
        """Slice out the kinetic parameters for one unit's network."""
        unit = self.units[unit_name]
        net = getattr(unit, "network", None)
        if net is None:
            return jnp.zeros((0,))
        start, size = self._parameter_layout.network_param_blocks[net.name]
        return jax.lax.dynamic_slice(params_full, (start,), (size,))

    def initial_state(self) -> jnp.ndarray:
        """Concatenated initial state from each unit's ``initial_state()``."""
        self._build_state_layout()
        if self._total_state_size == 0:
            return jnp.zeros((0,))
        pieces: list[jnp.ndarray] = []
        for name in self._unit_order:
            pieces.append(self.units[name].initial_state())
        return jnp.concatenate(pieces)

    # ----- RHS -------------------------------------------------------------

    def _rhs(
        self,
        t: jnp.ndarray,
        state_full: jnp.ndarray,
        params_full: jnp.ndarray,
    ) -> jnp.ndarray:
        # Step 1: split state by unit.
        states: dict[str, jnp.ndarray] = {}
        for name in self._unit_order:
            start, size = self._state_layout[name]
            states[name] = jax.lax.dynamic_slice(state_full, (start,), (size,))

        # Step 2: build the stream registry, starting with influents and
        # initial-value seeds for recycle edges.
        streams: dict[tuple[Optional[str], str], Stream] = {}
        for port_name, series in self.influents.items():
            streams[(None, port_name)] = series.at(t)
        # Pre-seed recycle edges so the downstream unit can read them on
        # the first iteration before the source unit has been visited.
        seeded: dict[tuple[str, str], Stream] = {}
        for conn in self.connections:
            if conn.from_unit is None:
                continue
            if conn.initial_value is not None:
                seeded[(conn.from_unit, conn.from_port)] = conn.initial_value

        # Step 3: traverse units in evaluation order, computing outputs.
        # Recycle edges (downstream → upstream) create cyclic data
        # dependencies. We resolve them by iterating the full set of unit
        # output computations multiple times: each iteration improves the
        # stream estimates on recycle edges. For typical BSM-family
        # topologies with 1-2 recycle loops, 3 passes are sufficient for
        # the streams to converge to consistent values within solver
        # tolerance. The iteration is cheap because every unit's
        # compute_outputs is a pure function of its (current-pass) inputs
        # and its known internal state.
        all_outputs: dict[tuple[str, str], Stream] = {}
        all_outputs.update(seeded)
        for _pass in range(3):
            for name in self._unit_order:
                unit = self.units[name]
                inputs = self._collect_inputs(name, all_outputs, streams)
                params_unit = self._params_for_unit(name, params_full)
                outputs = unit.compute_outputs(t, states[name], inputs, params_unit)
                for port, stream in outputs.items():
                    all_outputs[(name, port)] = stream
                    streams[(name, port)] = stream

        # Step 4: compute dstates from final input streams.
        dstates: list[jnp.ndarray] = []
        for name in self._unit_order:
            unit = self.units[name]
            inputs = self._collect_inputs(name, all_outputs, streams)
            params_unit = self._params_for_unit(name, params_full)
            dstate = unit.rhs(t, states[name], inputs, params_unit)
            dstates.append(dstate)
        return jnp.concatenate(dstates) if dstates else jnp.zeros((0,))

    def _collect_inputs(
        self,
        unit_name: str,
        all_outputs: dict[tuple[str, str], Stream],
        streams: dict[tuple[Optional[str], str], Stream],
    ) -> dict[str, Stream]:
        """Find the input stream for each port of ``unit_name``."""
        inputs: dict[str, Stream] = {}
        for conn in self.connections:
            if conn.to_unit != unit_name:
                continue
            if conn.from_unit is None:
                src = streams[(None, conn.from_port)]
            else:
                key = (conn.from_unit, conn.from_port)
                if key in all_outputs:
                    src = all_outputs[key]
                elif key in streams:
                    src = streams[key]
                else:
                    raise RuntimeError(
                        f"Stream {conn.from_unit}.{conn.from_port} not yet "
                        f"available for {conn.to_unit}.{conn.to_port}. "
                        f"Recycle edges must be seeded with initial_value."
                    )
            inputs[conn.to_port] = src.with_C(conn.translator.translate(src.C))
        return inputs

    # ----- solve -----------------------------------------------------------

    def solve(
        self,
        t_span: tuple[float, float],
        t_eval: Union[jnp.ndarray, None] = None,
        params: Optional[jnp.ndarray] = None,
        *,
        rtol: float = 1e-6,
        atol: Union[float, jnp.ndarray] = 1e-9,
        adjoint: Optional[diffrax.AbstractAdjoint] = None,
        dtmax: Optional[float] = None,
        max_steps: int = 100_000,
    ) -> PlantSolution:
        """Integrate the plant over ``t_span``.

        Parameters
        ----------
        t_span : (float, float)
            ``(t_start, t_end)`` in plant time units (typically days for BSM-family).
        t_eval : jnp.ndarray, optional
            Save times. If ``None`` only the endpoint is saved.
        params : jnp.ndarray, optional
            Flat plant parameter vector. Defaults to :meth:`default_parameters`.
        rtol, atol : solver tolerances.
        adjoint : diffrax adjoint strategy.
        dtmax : float, optional
            Maximum integrator step (threaded into the PIDController). Default
            ``None`` (uncapped) is fastest for forward solves. Set it for a
            stiff plant when *differentiating* through the solve: the
            reverse-mode adjoint of stiff biofilm reactions returns non-finite
            values uncapped, and capping ``dtmax`` to a small multiple of the
            fastest reaction timescale restores finite gradients (same as the
            reactor ``dtmax``; see the stiff-network discussion in CLAUDE.md).
        max_steps : int, optional
            Maximum number of internal solver steps (default 100000). Increase
            it for stiff, long-horizon plants -- notably BSM1 with the Takács
            clarifier, whose 10-layer settling dynamics need a larger budget than
            the stateless ``IdealClarifier``.

        Returns
        -------
        PlantSolution
        """
        self._build_state_layout()
        layout = self._build_parameter_layout()
        if params is None:
            params = self.default_parameters()
        else:
            params = jnp.asarray(params)
            if params.shape != (layout.total_size,):
                raise ValueError(
                    f"params has shape {params.shape}, expected "
                    f"({layout.total_size},)"
                )
        atol_eff = _coerce_atol(atol, self._total_state_size)

        y0 = self.initial_state()
        t0, t1 = float(t_span[0]), float(t_span[1])
        if not (t1 > t0):
            raise ValueError(f"t_span end must exceed start; got ({t0}, {t1}).")
        if t_eval is None:
            saveat = diffrax.SaveAt(t1=True)
        else:
            t_eval = jnp.asarray(t_eval)
            saveat = diffrax.SaveAt(ts=t_eval)

        # Closure-capture self and params; Diffrax sees a clean (t, y, args)
        # signature. We pass params via args so jax.grad through params
        # works.
        def rhs(t, y, args):
            return self._rhs(t, y, args)

        sol = _run_diffeqsolve(
            rhs,
            t0=t0,
            t1=t1,
            y0=y0,
            args=params,
            saveat=saveat,
            rtol=rtol,
            atol=atol_eff,
            adjoint=adjoint,
            dtmax=dtmax,
            max_steps=max_steps,
        )
        return PlantSolution(t=sol.ts, state=sol.ys, plant=self)
